### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by wasyl00** [buba447/simpsonstv#2]
Awesome project. Thanks for sharing!

I'm still waiting for the hardware so cannot test anything but wanted to encode stuff in advance hence the question. Wanted to know why 480p height? Is it based on performance testing? Also its a little unusual to give height as base resolution. Normally I saw width of the video as base for resizing. Is the Rpi zero w  not able to run native screen size 640x480 res? Quality would look best in native res. Thanks

**Comment by Diegus83** [comment]
I can't speak for the author but 640x480 is width x height, the screen is 640x480 as well, so if the videos you are encoding are from a 4:3 source, the final result will be 640x480. If the aspect ratio is different (let's say the modern 16:9 crop of the episodes) the video will still be 480 height but wider and (I'm guessing here since I don't have the hardware to try) the video will still fill the whole screen and the extra pixels on the sides will be lost. I think this is a valid approach for such a small screen since wasting pixels in letter boxing seems unnecessary. If you encode based on width you could end up with a 640x360 video and wasting pixels in black bars at the top and bottom.

I think this may also be why in the original Reddit post he went with the first 11 seasons, those you can rip from your own DVDs and are in the original 4:3 aspect ratio (actually the first 20 season where originally aired in 4:3 it seems).
